apiVersion: v1
kind: Pod
metadata:
  name: system-under-test
spec:
  volumes:
    - name: test-results
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: helloworld
      image: helloworld:1.0
      volumeMounts:
        - name: test-results
          mountPath: "/home/node/app/tests/results"
